version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/waste_management
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=False
    depends_on:
      - db
    volumes:
      - ./frontend:/app/frontend:ro
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=waste_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html/static:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data: